// pages/api/countrydata.js - Ülkelere göre priz, sağlık, koordinat

const COUNTRY_DATA = {
  ID: { name:'Endonezya', flag:'🇮🇩', city:'Bali', lat:-8.34, lon:115.09, plugs:['C','F'], voltage:'220V', freq:'50Hz', trCompat:true, volcano:true, tsunami:true, earthquake:true,
    health:[{name:'Tifo',level:'required'},{name:'Hepatit A & B',level:'recommended'},{name:'Sıtma (bazı bölgeler)',level:'regional'},{name:'Dengue Humması',level:'warning'},{name:'Kuduz',level:'recommended'},{name:'Kolera (risk düşük)',level:'regional'},{name:'COVID-19',level:'ok'}]},
  TH: { name:'Tayland', flag:'🇹🇭', city:'Bangkok', lat:13.76, lon:100.50, plugs:['A','B','C'], voltage:'220V', freq:'50Hz', trCompat:false, volcano:false, tsunami:false, earthquake:false,
    health:[{name:'Hepatit A & B',level:'recommended'},{name:'Tifo',level:'recommended'},{name:'Sıtma (kuzey/sınır bölgeler)',level:'regional'},{name:'Dengue',level:'warning'},{name:'Japon Ensefaliti',level:'regional'},{name:'COVID-19',level:'ok'}]},
  JP: { name:'Japonya', flag:'🇯🇵', city:'Tokyo', lat:35.68, lon:139.65, plugs:['A','B'], voltage:'100V', freq:'50/60Hz', trCompat:false, volcano:true, tsunami:true, earthquake:true,
    health:[{name:'Hepatit A',level:'recommended'},{name:'Japon Ensefaliti',level:'regional'},{name:'Kuduz (hayvan teması)',level:'recommended'},{name:'COVID-19',level:'ok'}]},
  SG: { name:'Singapur', flag:'🇸🇬', city:'Singapur', lat:1.35, lon:103.82, plugs:['G'], voltage:'230V', freq:'50Hz', trCompat:false, volcano:false, tsunami:false, earthquake:false,
    health:[{name:'Hepatit A',level:'recommended'},{name:'Dengue (şehir içi risk)',level:'warning'},{name:'COVID-19',level:'ok'}]},
  VN: { name:'Vietnam', flag:'🇻🇳', city:'Ho Chi Minh', lat:10.82, lon:106.63, plugs:['A','C','F'], voltage:'220V', freq:'50Hz', trCompat:true, volcano:false, tsunami:false, earthquake:false,
    health:[{name:'Hepatit A & B',level:'recommended'},{name:'Tifo',level:'recommended'},{name:'Sıtma (kırsal kuzey/güney)',level:'regional'},{name:'Dengue',level:'warning'},{name:'Kuduz',level:'recommended'}]},
  MY: { name:'Malezya', flag:'🇲🇾', city:'Kuala Lumpur', lat:3.14, lon:101.69, plugs:['G'], voltage:'240V', freq:'50Hz', trCompat:false, volcano:false, tsunami:false, earthquake:false,
    health:[{name:'Hepatit A',level:'recommended'},{name:'Tifo',level:'recommended'},{name:'Sıtma (Borneo/ormanlık)',level:'regional'},{name:'Dengue',level:'warning'}]},
  IN: { name:'Hindistan', flag:'🇮🇳', city:'New Delhi', lat:28.61, lon:77.21, plugs:['C','D','M'], voltage:'230V', freq:'50Hz', trCompat:true, volcano:false, tsunami:false, earthquake:true,
    health:[{name:'Tifo',level:'required'},{name:'Hepatit A & B',level:'recommended'},{name:'Sıtma',level:'regional'},{name:'Kolera',level:'regional'},{name:'Kuduz',level:'recommended'},{name:'Japon Ensefaliti',level:'regional'}]},
  MM: { name:'Myanmar', flag:'🇲🇲', city:'Yangon', lat:16.87, lon:96.19, plugs:['C','D','F','G','I'], voltage:'230V', freq:'50Hz', trCompat:true, volcano:false, tsunami:false, earthquake:true,
    health:[{name:'Sıtma',level:'required'},{name:'Tifo',level:'recommended'},{name:'Hepatit A & B',level:'recommended'},{name:'Dengue',level:'warning'},{name:'Kuduz',level:'recommended'}]},
  KH: { name:'Kamboçya', flag:'🇰🇭', city:'Phnom Penh', lat:11.56, lon:104.92, plugs:['A','C','G'], voltage:'230V', freq:'50Hz', trCompat:true, volcano:false, tsunami:false, earthquake:false,
    health:[{name:'Tifo',level:'recommended'},{name:'Hepatit A & B',level:'recommended'},{name:'Sıtma (ormanlık)',level:'regional'},{name:'Dengue',level:'warning'},{name:'Kuduz',level:'recommended'}]},
  PH: { name:'Filipinler', flag:'🇵🇭', city:'Manila', lat:14.60, lon:120.98, plugs:['A','B','C'], voltage:'220V', freq:'60Hz', trCompat:false, volcano:true, tsunami:true, earthquake:true,
    health:[{name:'Tifo',level:'recommended'},{name:'Hepatit A & B',level:'recommended'},{name:'Dengue',level:'warning'},{name:'Kuduz',level:'recommended'},{name:'Sıtma (güney adalar)',level:'regional'}]},
  LK: { name:'Sri Lanka', flag:'🇱🇰', city:'Colombo', lat:6.93, lon:79.85, plugs:['D','G','M'], voltage:'230V', freq:'50Hz', trCompat:false, volcano:false, tsunami:true, earthquake:false,
    health:[{name:'Hepatit A',level:'recommended'},{name:'Tifo',level:'recommended'},{name:'Sıtma (kuzey)',level:'regional'},{name:'Dengue',level:'warning'}]},
  MV: { name:'Maldivler', flag:'🇲🇻', city:'Malé', lat:4.17, lon:73.51, plugs:['G','J','K'], voltage:'230V', freq:'50Hz', trCompat:false, volcano:false, tsunami:true, earthquake:false,
    health:[{name:'Hepatit A',level:'recommended'},{name:'Tifo',level:'recommended'},{name:'COVID-19',level:'ok'}]},
  NP: { name:'Nepal', flag:'🇳🇵', city:'Katmandu', lat:27.70, lon:85.32, plugs:['C','D','M'], voltage:'230V', freq:'50Hz', trCompat:true, volcano:false, tsunami:false, earthquake:true,
    health:[{name:'Tifo',level:'required'},{name:'Hepatit A & B',level:'recommended'},{name:'Kuduz',level:'recommended'},{name:'Japon Ensefaliti',level:'regional'},{name:'Malaria (düşük irtifa)',level:'regional'}]},
  AE: { name:'BAE', flag:'🇦🇪', city:'Dubai', lat:25.20, lon:55.27, plugs:['G'], voltage:'220V', freq:'50Hz', trCompat:false, volcano:false, tsunami:false, earthquake:false,
    health:[{name:'COVID-19',level:'ok'},{name:'Hepatit A',level:'recommended'},{name:'Standart aşılar güncel olsun',level:'recommended'}]},
  QA: { name:'Katar', flag:'🇶🇦', city:'Doha', lat:25.29, lon:51.53, plugs:['D','G'], voltage:'240V', freq:'50Hz', trCompat:false, volcano:false, tsunami:false, earthquake:false,
    health:[{name:'COVID-19',level:'ok'},{name:'Hepatit A',level:'recommended'}]},
  JO: { name:'Ürdün', flag:'🇯🇴', city:'Amman', lat:31.95, lon:35.93, plugs:['B','C','D','F','G','J'], voltage:'230V', freq:'50Hz', trCompat:true, volcano:false, tsunami:false, earthquake:true,
    health:[{name:'Hepatit A',level:'recommended'},{name:'Tifo',level:'recommended'},{name:'Kuduz',level:'regional'}]},
  AM: { name:'Ermenistan', flag:'🇦🇲', city:'Erivan', lat:40.18, lon:44.51, plugs:['C','F'], voltage:'230V', freq:'50Hz', trCompat:true, volcano:false, tsunami:false, earthquake:true,
    health:[{name:'Hepatit A',level:'recommended'},{name:'Tifo',level:'recommended'}]},
  GE: { name:'Gürcistan', flag:'🇬🇪', city:'Tiflis', lat:41.69, lon:44.83, plugs:['C','F'], voltage:'220V', freq:'50Hz', trCompat:true, volcano:false, tsunami:false, earthquake:true,
    health:[{name:'Hepatit A',level:'recommended'},{name:'Kuduz',level:'recommended'}]},
  AZ: { name:'Azerbaycan', flag:'🇦🇿', city:'Bakü', lat:40.41, lon:49.87, plugs:['C','F'], voltage:'220V', freq:'50Hz', trCompat:true, volcano:false, tsunami:false, earthquake:true,
    health:[{name:'Hepatit A',level:'recommended'},{name:'Tifo',level:'recommended'}]},
  UZ: { name:'Özbekistan', flag:'🇺🇿', city:'Taşkent', lat:41.30, lon:69.24, plugs:['C','F','I'], voltage:'220V', freq:'50Hz', trCompat:true, volcano:false, tsunami:false, earthquake:true,
    health:[{name:'Tifo',level:'recommended'},{name:'Hepatit A',level:'recommended'},{name:'Kuduz',level:'regional'}]},
  // AVRUPA
  FR: { name:'Fransa', flag:'🇫🇷', city:'Paris', lat:48.86, lon:2.35, plugs:['C','E'], voltage:'230V', freq:'50Hz', trCompat:true, volcano:false, tsunami:false, earthquake:false,
    health:[{name:'COVID-19',level:'ok'},{name:'Standart Avrupa aşıları',level:'recommended'}]},
  ES: { name:'İspanya', flag:'🇪🇸', city:'Madrid', lat:40.42, lon:-3.70, plugs:['C','F'], voltage:'230V', freq:'50Hz', trCompat:true, volcano:false, tsunami:false, earthquake:true,
    health:[{name:'COVID-19',level:'ok'},{name:'Standart Avrupa aşıları',level:'recommended'}]},
  IT: { name:'İtalya', flag:'🇮🇹', city:'Roma', lat:41.90, lon:12.50, plugs:['C','F','L'], voltage:'230V', freq:'50Hz', trCompat:true, volcano:true, tsunami:false, earthquake:true,
    health:[{name:'COVID-19',level:'ok'},{name:'Standart Avrupa aşıları',level:'recommended'}]},
  DE: { name:'Almanya', flag:'🇩🇪', city:'Berlin', lat:52.52, lon:13.41, plugs:['C','F'], voltage:'230V', freq:'50Hz', trCompat:true, volcano:false, tsunami:false, earthquake:false,
    health:[{name:'COVID-19',level:'ok'},{name:'Standart Avrupa aşıları',level:'recommended'}]},
  GB: { name:'İngiltere', flag:'🇬🇧', city:'Londra', lat:51.51, lon:-0.13, plugs:['G'], voltage:'230V', freq:'50Hz', trCompat:false, volcano:false, tsunami:false, earthquake:false,
    health:[{name:'COVID-19',level:'ok'},{name:'Standart Avrupa aşıları',level:'recommended'}]},
  GR: { name:'Yunanistan', flag:'🇬🇷', city:'Atina', lat:37.98, lon:23.73, plugs:['C','F'], voltage:'230V', freq:'50Hz', trCompat:true, volcano:true, tsunami:false, earthquake:true,
    health:[{name:'COVID-19',level:'ok'},{name:'Hepatit A',level:'recommended'}]},
  PT: { name:'Portekiz', flag:'🇵🇹', city:'Lizbon', lat:38.72, lon:-9.14, plugs:['C','F'], voltage:'230V', freq:'50Hz', trCompat:true, volcano:false, tsunami:true, earthquake:true,
    health:[{name:'COVID-19',level:'ok'},{name:'Standart Avrupa aşıları',level:'recommended'}]},
  NL: { name:'Hollanda', flag:'🇳🇱', city:'Amsterdam', lat:52.37, lon:4.90, plugs:['C','F'], voltage:'230V', freq:'50Hz', trCompat:true, volcano:false, tsunami:false, earthquake:false,
    health:[{name:'COVID-19',level:'ok'},{name:'Standart Avrupa aşıları',level:'recommended'}]},
  CH: { name:'İsviçre', flag:'🇨🇭', city:'Zürih', lat:47.38, lon:8.54, plugs:['J'], voltage:'230V', freq:'50Hz', trCompat:false, volcano:false, tsunami:false, earthquake:false,
    health:[{name:'COVID-19',level:'ok'},{name:'Standart Avrupa aşıları',level:'recommended'}]},
  AT: { name:'Avusturya', flag:'🇦🇹', city:'Viyana', lat:48.21, lon:16.37, plugs:['C','F'], voltage:'230V', freq:'50Hz', trCompat:true, volcano:false, tsunami:false, earthquake:false,
    health:[{name:'COVID-19',level:'ok'},{name:'FSME (Kene ensefaliti)',level:'regional'}]},
  BE: { name:'Belçika', flag:'🇧🇪', city:'Brüksel', lat:50.85, lon:4.35, plugs:['E'], voltage:'230V', freq:'50Hz', trCompat:true, volcano:false, tsunami:false, earthquake:false,
    health:[{name:'COVID-19',level:'ok'}]},
  NO: { name:'Norveç', flag:'🇳🇴', city:'Oslo', lat:59.91, lon:10.75, plugs:['C','F'], voltage:'230V', freq:'50Hz', trCompat:true, volcano:false, tsunami:false, earthquake:false,
    health:[{name:'COVID-19',level:'ok'}]},
  SE: { name:'İsveç', flag:'🇸🇪', city:'Stockholm', lat:59.33, lon:18.07, plugs:['C','F'], voltage:'230V', freq:'50Hz', trCompat:true, volcano:false, tsunami:false, earthquake:false,
    health:[{name:'COVID-19',level:'ok'}]},
  DK: { name:'Danimarka', flag:'🇩🇰', city:'Kopenhag', lat:55.68, lon:12.57, plugs:['C','F','K'], voltage:'230V', freq:'50Hz', trCompat:true, volcano:false, tsunami:false, earthquake:false,
    health:[{name:'COVID-19',level:'ok'}]},
  FI: { name:'Finlandiya', flag:'🇫🇮', city:'Helsinki', lat:60.17, lon:24.94, plugs:['C','F'], voltage:'230V', freq:'50Hz', trCompat:true, volcano:false, tsunami:false, earthquake:false,
    health:[{name:'COVID-19',level:'ok'}]},
  CZ: { name:'Çek Cumhuriyeti', flag:'🇨🇿', city:'Prag', lat:50.08, lon:14.44, plugs:['C','E'], voltage:'230V', freq:'50Hz', trCompat:true, volcano:false, tsunami:false, earthquake:false,
    health:[{name:'COVID-19',level:'ok'}]},
  PL: { name:'Polonya', flag:'🇵🇱', city:'Varşova', lat:52.23, lon:21.01, plugs:['C','E'], voltage:'230V', freq:'50Hz', trCompat:true, volcano:false, tsunami:false, earthquake:false,
    health:[{name:'COVID-19',level:'ok'},{name:'FSME (doğu bölgeler)',level:'regional'}]},
  HU: { name:'Macaristan', flag:'🇭🇺', city:'Budapeşte', lat:47.50, lon:19.04, plugs:['C','F'], voltage:'230V', freq:'50Hz', trCompat:true, volcano:false, tsunami:false, earthquake:false,
    health:[{name:'COVID-19',level:'ok'}]},
  HR: { name:'Hırvatistan', flag:'🇭🇷', city:'Zagreb', lat:45.81, lon:15.98, plugs:['C','F'], voltage:'230V', freq:'50Hz', trCompat:true, volcano:false, tsunami:false, earthquake:true,
    health:[{name:'COVID-19',level:'ok'},{name:'Hepatit A',level:'recommended'}]},
  // AMERİKA
  US: { name:'ABD', flag:'🇺🇸', city:'New York', lat:40.71, lon:-74.01, plugs:['A','B'], voltage:'120V', freq:'60Hz', trCompat:false, volcano:false, tsunami:false, earthquake:true,
    health:[{name:'COVID-19',level:'ok'},{name:'Hepatit A & B',level:'recommended'}]},
  CA: { name:'Kanada', flag:'🇨🇦', city:'Toronto', lat:43.65, lon:-79.38, plugs:['A','B'], voltage:'120V', freq:'60Hz', trCompat:false, volcano:false, tsunami:false, earthquake:true,
    health:[{name:'COVID-19',level:'ok'},{name:'Hepatit A',level:'recommended'}]},
  MX: { name:'Meksika', flag:'🇲🇽', city:'Cancun', lat:21.16, lon:-86.85, plugs:['A','B'], voltage:'127V', freq:'60Hz', trCompat:false, volcano:true, tsunami:false, earthquake:true,
    health:[{name:'Hepatit A',level:'recommended'},{name:'Tifo',level:'recommended'},{name:'Sıtma (kırsal)',level:'regional'},{name:'Dengue',level:'warning'},{name:'Zika (bazı bölgeler)',level:'warning'}]},
  BR: { name:'Brezilya', flag:'🇧🇷', city:'São Paulo', lat:-23.55, lon:-46.63, plugs:['C','N'], voltage:'127/220V', freq:'60Hz', trCompat:true, volcano:false, tsunami:false, earthquake:false,
    health:[{name:'Sarı Humma',level:'required'},{name:'Sıtma (Amazon)',level:'regional'},{name:'Dengue',level:'warning'},{name:'Zika',level:'warning'},{name:'Hepatit A',level:'recommended'}]},
  AR: { name:'Arjantin', flag:'🇦🇷', city:'Buenos Aires', lat:-34.60, lon:-58.38, plugs:['C','I'], voltage:'220V', freq:'50Hz', trCompat:true, volcano:true, tsunami:false, earthquake:true,
    health:[{name:'Hepatit A',level:'recommended'},{name:'Tifo',level:'recommended'},{name:'Sarı Humma (kuzey)',level:'regional'}]},
  CU: { name:'Küba', flag:'🇨🇺', city:'Havana', lat:23.14, lon:-82.36, plugs:['A','B','C','L'], voltage:'110/220V', freq:'60Hz', trCompat:false, volcano:false, tsunami:false, earthquake:true,
    health:[{name:'Hepatit A',level:'recommended'},{name:'Tifo',level:'recommended'},{name:'Dengue',level:'warning'}]},
  // AFRİKA
  MA: { name:'Fas', flag:'🇲🇦', city:'Marakeş', lat:31.63, lon:-7.98, plugs:['C','E'], voltage:'220V', freq:'50Hz', trCompat:true, volcano:false, tsunami:false, earthquake:true,
    health:[{name:'Hepatit A',level:'recommended'},{name:'Tifo',level:'recommended'},{name:'Kuduz',level:'regional'}]},
  EG: { name:'Mısır', flag:'🇪🇬', city:'Hurghada', lat:27.26, lon:33.81, plugs:['C','F'], voltage:'220V', freq:'50Hz', trCompat:true, volcano:false, tsunami:false, earthquake:true,
    health:[{name:'Hepatit A',level:'recommended'},{name:'Tifo',level:'recommended'},{name:'Kolera',level:'regional'},{name:'Kuduz',level:'regional'}]},
  TN: { name:'Tunus', flag:'🇹🇳', city:'Tunus', lat:36.82, lon:10.17, plugs:['C','E'], voltage:'230V', freq:'50Hz', trCompat:true, volcano:false, tsunami:false, earthquake:true,
    health:[{name:'Hepatit A',level:'recommended'},{name:'Tifo',level:'recommended'}]},
  ZA: { name:'Güney Afrika', flag:'🇿🇦', city:'Cape Town', lat:-33.92, lon:18.42, plugs:['M','N','C'], voltage:'230V', freq:'50Hz', trCompat:false, volcano:false, tsunami:false, earthquake:false,
    health:[{name:'Sıtma (Kruger/kuzey)',level:'regional'},{name:'Hepatit A & B',level:'recommended'},{name:'Sarı Humma (bazı bölgeler)',level:'regional'},{name:'Kuduz',level:'recommended'}]},
  KE: { name:'Kenya', flag:'🇰🇪', city:'Nairobi', lat:-1.29, lon:36.82, plugs:['G'], voltage:'240V', freq:'50Hz', trCompat:false, volcano:false, tsunami:false, earthquake:true,
    health:[{name:'Sıtma',level:'required'},{name:'Sarı Humma',level:'required'},{name:'Tifo',level:'recommended'},{name:'Hepatit A & B',level:'recommended'},{name:'Kuduz',level:'recommended'}]},
  ET: { name:'Etiyopya', flag:'🇪🇹', city:'Addis Ababa', lat:9.03, lon:38.74, plugs:['C','E','F','L'], voltage:'220V', freq:'50Hz', trCompat:true, volcano:false, tsunami:false, earthquake:true,
    health:[{name:'Sıtma',level:'required'},{name:'Sarı Humma',level:'required'},{name:'Tifo',level:'recommended'},{name:'Hepatit A',level:'recommended'},{name:'Kuduz',level:'recommended'}]},
  // OKYANUSYA
  AU: { name:'Avustralya', flag:'🇦🇺', city:'Sydney', lat:-33.87, lon:151.21, plugs:['I'], voltage:'230V', freq:'50Hz', trCompat:false, volcano:false, tsunami:false, earthquake:false,
    health:[{name:'COVID-19',level:'ok'},{name:'Hepatit A',level:'recommended'}]},
  NZ: { name:'Yeni Zelanda', flag:'🇳🇿', city:'Auckland', lat:-36.85, lon:174.76, plugs:['I'], voltage:'230V', freq:'50Hz', trCompat:false, volcano:true, tsunami:true, earthquake:true,
    health:[{name:'COVID-19',level:'ok'},{name:'Hepatit A',level:'recommended'}]},
  FJ: { name:'Fiji', flag:'🇫🇯', city:'Nadi', lat:-17.71, lon:178.06, plugs:['I'], voltage:'240V', freq:'50Hz', trCompat:false, volcano:false, tsunami:true, earthquake:true,
    health:[{name:'Tifo',level:'recommended'},{name:'Hepatit A',level:'recommended'},{name:'Dengue',level:'warning'},{name:'Sıtma (bazı adalar)',level:'regional'}]},
};

// IATA → ülke kodu
const IATA_MAP = {
  DPS:'ID',CGK:'ID',SUB:'ID',UPG:'ID',BKK:'TH',HKT:'TH',CNX:'TH',USM:'TH',NRT:'JP',KIX:'JP',CTS:'JP',FUK:'JP',OKA:'JP',NGO:'JP',SIN:'SG',SGN:'VN',HAN:'VN',DAD:'VN',KUL:'MY',PEN:'MY',LGK:'MY',DEL:'IN',BOM:'IN',MAA:'IN',BLR:'IN',CCU:'IN',HYD:'IN',GOI:'IN',RGN:'MM',PNH:'KH',REP:'KH',MNL:'PH',CEB:'PH',CMB:'LK',MLE:'MV',KTM:'NP',DXB:'AE',AUH:'AE',SHJ:'AE',DOH:'QA',AMM:'JO',AQJ:'JO',EVN:'AM',TBS:'GE',GYD:'AZ',TAS:'UZ',
  CDG:'FR',ORY:'FR',NCE:'FR',LYS:'FR',MRS:'FR',BOD:'FR',TLS:'FR',NTE:'FR',MAD:'ES',BCN:'ES',AGP:'ES',PMI:'ES',VLC:'ES',SVQ:'ES',TFS:'ES',LPA:'ES',IBZ:'ES',FCO:'IT',MXP:'IT',VCE:'IT',NAP:'IT',CTA:'IT',PMO:'IT',BLQ:'IT',FRA:'DE',MUC:'DE',BER:'DE',DUS:'DE',HAM:'DE',CGN:'DE',STR:'DE',NUE:'DE',LHR:'GB',LGW:'GB',MAN:'GB',EDI:'GB',BHX:'GB',STN:'GB',GLA:'GB',ATH:'GR',HER:'GR',RHO:'GR',SKG:'GR',CFU:'GR',KGS:'GR',JMK:'GR',JTR:'GR',CHQ:'GR',LIS:'PT',OPO:'PT',FAO:'PT',FNC:'PT',AMS:'NL',RTM:'NL',ZRH:'CH',GVA:'CH',BSL:'CH',VIE:'AT',GRZ:'AT',SZG:'AT',BRU:'BE',OSL:'NO',ARN:'SE',GOT:'SE',CPH:'DK',HEL:'FI',PRG:'CZ',WAW:'PL',KRK:'PL',BUD:'HU',ZAG:'HR',SPU:'HR',DBV:'HR',
  JFK:'US',LAX:'US',ORD:'US',MIA:'US',SFO:'US',LAS:'US',MCO:'US',SEA:'US',BOS:'US',DFW:'US',ATL:'US',IAH:'US',EWR:'US',YYZ:'CA',YVR:'CA',YUL:'CA',CUN:'MX',MEX:'MX',SJD:'MX',GDL:'MX',GRU:'BR',GIG:'BR',SSA:'BR',REC:'BR',EZE:'AR',AEP:'AR',HAV:'CU',
  RAK:'MA',CMN:'MA',AGA:'MA',TNG:'MA',CAI:'EG',HRG:'EG',SSH:'EG',LXR:'EG',ASW:'EG',TUN:'TN',CPT:'ZA',JNB:'ZA',NBO:'KE',MBA:'KE',ADD:'ET',
  SYD:'AU',MEL:'AU',BNE:'AU',PER:'AU',CNS:'AU',AKL:'NZ',CHC:'NZ',WLG:'NZ',NAN:'FJ',
};

export function getCountryFromIATA(iata) {
  const code = IATA_MAP[iata?.toUpperCase()];
  return code ? COUNTRY_DATA[code] : null;
}

export default function handler(req, res) {
  const { iata } = req.query;
  const data = getCountryFromIATA(iata);
  if (!data) return res.status(404).json({ error: `${iata} için ülke verisi bulunamadı` });
  return res.status(200).json(data);
}
