// pages/api/visa.js - Genişletilmiş vize veritabanı

const VISA_DATA = {
  TR: { // Türk pasaportu
    // ASYA
    ID: { type:'voa', name:'Vize on Arrival / e-VoA', duration:30, fee:'500.000 IDR (~€30)', extendable:true, notes:'Havalimanında veya molina.imigrasi.go.id üzerinden e-VoA alın.', link:'https://molina.imigrasi.go.id' },
    TH: { type:'free', name:'Vizesiz', duration:30, fee:null, notes:'Pasaport min. 6 ay geçerli olmalı. Dönüş bileti gerekli.' },
    JP: { type:'free', name:'Vizesiz', duration:90, fee:null, notes:'2023 sonrası Türk vatandaşları için vizesiz. Pasaport 6 ay geçerli olmalı.' },
    SG: { type:'free', name:'Vizesiz', duration:30, fee:null, notes:'Singapur — 30 gün vizesiz giriş.' },
    VN: { type:'evisa', name:'e-Vize', duration:90, fee:'25 USD', notes:'evisa.xuatnhapcanh.gov.vn üzerinden online başvurun. 3 iş günü.' },
    MY: { type:'free', name:'Vizesiz', duration:90, fee:null, notes:'Malezya — 3 aya kadar vizesiz.' },
    IN: { type:'evisa', name:'e-Vize (e-Tourist Visa)', duration:60, fee:'25 USD', notes:'indianvisaonline.gov.in — seyahatten en az 4 gün önce başvurun.' },
    MM: { type:'evisa', name:'e-Vize', duration:28, fee:'50 USD', notes:'evisa.moip.gov.mm üzerinden başvurun.' },
    KH: { type:'voa', name:'Vize on Arrival / e-Vize', duration:30, fee:'35 USD', notes:'Kamboçya — havalimanında veya evisa.gov.kh online.' },
    PH: { type:'free', name:'Vizesiz', duration:30, fee:null, notes:'Filipinler — 30 gün vizesiz. Uzatılabilir.' },
    LK: { type:'eta', name:'ETA (Electronic Travel Authorization)', duration:30, fee:'20 USD', notes:'eta.gov.lk üzerinden online başvurun.' },
    MV: { type:'free', name:'Vizesiz (VoA)', duration:30, fee:null, notes:'Maldivler — varışta ücretsiz vizesiz giriş.' },
    NP: { type:'voa', name:'Vize on Arrival', duration:30, fee:'30 USD', notes:'Nepal — havalimanında veya konsolosluktan.' },
    AE: { type:'voa', name:'Vize on Arrival — Ücretsiz', duration:30, fee:'Ücretsiz', notes:'Dubai/Abu Dhabi havalimanlarında otomatik 30 gün.' },
    QA: { type:'free', name:'Vizesiz', duration:30, fee:null, notes:'Katar — vizesiz giriş.' },
    JO: { type:'voa', name:'Vize on Arrival', duration:30, fee:'40 JOD', notes:'Ürdün — havalimanında alınabilir veya visa.gov.jo online.' },
    AM: { type:'free', name:'Vizesiz', duration:90, fee:null, notes:'Ermenistan — 3 ay vizesiz.' },
    GE: { type:'free', name:'Vizesiz', duration:365, fee:null, notes:'Gürcistan — 1 yıl vizesiz!' },
    AZ: { type:'evisa', name:'e-Vize (ASAN Visa)', duration:30, fee:'20 AZN', notes:'evisa.gov.az üzerinden 3 iş günü.' },
    UZ: { type:'free', name:'Vizesiz', duration:30, fee:null, notes:'Özbekistan — 30 gün vizesiz.' },
    // AVRUPA - Schengen
    FR: { type:'schengen', name:'Schengen Vizesi Gerekli', duration:90, fee:'80€', notes:'Fransız Konsolosluğu veya TLScontact üzerinden başvurun. Rezervasyon, sigorta, mali yeterlilik belgesi gerekli.' },
    ES: { type:'schengen', name:'Schengen Vizesi Gerekli', duration:90, fee:'80€', notes:'İspanya Konsolosluğu — Turizm C tipi vize. 4-6 hafta süre.' },
    IT: { type:'schengen', name:'Schengen Vizesi Gerekli', duration:90, fee:'80€', notes:'İtalyan Konsolosluğu veya VFS Global. 3-4 hafta.' },
    DE: { type:'schengen', name:'Schengen Vizesi Gerekli', duration:90, fee:'80€', notes:'Alman Konsolosluğu — Randevu gerekli, 6-8 hafta önceden alın.' },
    GB: { type:'visa', name:'Standart Ziyaretçi Vizesi', duration:180, fee:'£115', notes:'UK Visas & Immigration — gov.uk/apply-standard-visitor-visa online başvuru.' },
    GR: { type:'schengen', name:'Schengen Vizesi Gerekli', duration:90, fee:'80€', notes:'Yunan Konsolosluğu — adalar için ek süre alınabilir.' },
    PT: { type:'schengen', name:'Schengen Vizesi Gerekli', duration:90, fee:'80€', notes:'Portekiz Konsolosluğu veya VFS Global.' },
    NL: { type:'schengen', name:'Schengen Vizesi Gerekli', duration:90, fee:'80€', notes:'Hollanda Konsolosluğu.' },
    CH: { type:'schengen', name:'Schengen Vizesi Gerekli', duration:90, fee:'80€', notes:'İsviçre Konsolosluğu — İsviçre Schengen üyesi.' },
    AT: { type:'schengen', name:'Schengen Vizesi Gerekli', duration:90, fee:'80€', notes:'Avusturya Konsolosluğu.' },
    BE: { type:'schengen', name:'Schengen Vizesi Gerekli', duration:90, fee:'80€', notes:'Belçika Konsolosluğu.' },
    NO: { type:'schengen', name:'Schengen Vizesi Gerekli', duration:90, fee:'80€', notes:'Norveç Konsolosluğu.' },
    SE: { type:'schengen', name:'Schengen Vizesi Gerekli', duration:90, fee:'80€', notes:'İsveç Konsolosluğu.' },
    DK: { type:'schengen', name:'Schengen Vizesi Gerekli', duration:90, fee:'80€', notes:'Danimarka Konsolosluğu.' },
    FI: { type:'schengen', name:'Schengen Vizesi Gerekli', duration:90, fee:'80€', notes:'Finlandiya Konsolosluğu.' },
    CZ: { type:'schengen', name:'Schengen Vizesi Gerekli', duration:90, fee:'80€', notes:'Çek Cumhuriyeti Konsolosluğu.' },
    PL: { type:'schengen', name:'Schengen Vizesi Gerekli', duration:90, fee:'80€', notes:'Polonya Konsolosluğu.' },
    HU: { type:'schengen', name:'Schengen Vizesi Gerekli', duration:90, fee:'80€', notes:'Macaristan Konsolosluğu.' },
    HR: { type:'schengen', name:'Schengen Vizesi Gerekli', duration:90, fee:'80€', notes:'Hırvatistan Konsolosluğu — 2023\'ten itibaren Schengen üyesi.' },
    // AMERİKA
    US: { type:'visa', name:'B1/B2 Turist Vizesi', duration:180, fee:'$185', notes:'travel.state.gov — Türkiye\'den randevu süresi uzun. En az 6 ay önceden başvurun. Parmak izi alınır.' },
    CA: { type:'eta', name:'eTA (Electronic Travel Authorization)', duration:180, fee:'CAD 7', notes:'canada.ca/en/immigration — Sadece uçuşla gidenlere uygulanır.' },
    MX: { type:'free', name:'Vizesiz', duration:180, fee:null, notes:'Meksika — 6 aya kadar vizesiz. Çok popüler Türk destinasyonu.' },
    BR: { type:'free', name:'Vizesiz', duration:90, fee:null, notes:'Brezilya — 2024\'ten itibaren Türk vatandaşlarına vizesiz.' },
    AR: { type:'free', name:'Vizesiz', duration:90, fee:null, notes:'Arjantin — vizesiz giriş.' },
    CU: { type:'voa', name:'Tourist Card', duration:30, fee:'25 CUC', notes:'Küba — havalimanında turist kartı alınır.' },
    // AFRİKA & ORTADOĞU
    MA: { type:'free', name:'Vizesiz', duration:90, fee:null, notes:'Fas — 3 ay vizesiz.' },
    EG: { type:'voa', name:'Vize on Arrival / e-Vize', duration:30, fee:'25 USD', notes:'Mısır — havalimanında veya visa2egypt.gov.eg online.' },
    TN: { type:'free', name:'Vizesiz', duration:90, fee:null, notes:'Tunus — vizesiz giriş.' },
    ZA: { type:'free', name:'Vizesiz', duration:30, fee:null, notes:'Güney Afrika — 30 gün vizesiz.' },
    KE: { type:'evisa', name:'e-Vize (eVisa Kenya)', duration:90, fee:'51 USD', notes:'evisa.go.ke üzerinden başvurun.' },
    ET: { type:'evisa', name:'e-Vize', duration:30, fee:'52 USD', notes:'Etiyopya — etour.gov.et online.' },
    // OKYANUSYA
    AU: { type:'eta', name:'ETA (subclass 601)', duration:90, fee:'AUD 20', notes:'immi.homeaffairs.gov.au — 24 saat içinde onay. Birden fazla giriş.' },
    NZ: { type:'nzeta', name:'NZeTA', duration:90, fee:'NZD 23', notes:'immigration.govt.nz — online başvuru, birkaç saat içinde onay.' },
    FJ: { type:'free', name:'Vizesiz', duration:120, fee:null, notes:'Fiji — 4 ay vizesiz!' },
  },
  CH: { // İsviçre pasaportu
    ID: { type:'voa', name:'Vize on Arrival', duration:30, fee:'500.000 IDR (~€30)', extendable:true },
    TH: { type:'free', name:'Vizesiz', duration:30, fee:null },
    JP: { type:'free', name:'Vizesiz', duration:90, fee:null },
    SG: { type:'free', name:'Vizesiz', duration:90, fee:null },
    VN: { type:'free', name:'Vizesiz', duration:45, fee:null, notes:'45 gün vizesiz giriş.' },
    IN: { type:'evisa', name:'e-Vize', duration:60, fee:'25 USD' },
    US: { type:'esta', name:'ESTA', duration:90, fee:'$21', notes:'esta.cbp.dhs.gov — seyahatten 72 saat önce başvurun.' },
    CA: { type:'eta', name:'eTA', duration:180, fee:'CAD 7' },
    AU: { type:'eta', name:'ETA', duration:90, fee:'AUD 20' },
    NZ: { type:'nzeta', name:'NZeTA', duration:90, fee:'NZD 23' },
    GB: { type:'free', name:'Vizesiz (Electronic Travel Authorisation)', duration:180, fee:'£10', notes:'2024\'ten itibaren ETA gerekiyor — gov.uk/apply-uk-visa.' },
    MA: { type:'free', name:'Vizesiz', duration:90, fee:null },
    EG: { type:'voa', name:'Vize on Arrival', duration:30, fee:'25 USD' },
    ZA: { type:'free', name:'Vizesiz', duration:90, fee:null },
    AE: { type:'free', name:'Vizesiz', duration:90, fee:null },
    MX: { type:'free', name:'Vizesiz', duration:180, fee:null },
    BR: { type:'free', name:'Vizesiz', duration:90, fee:null },
    // Schengen - İsviçre zaten Schengen içinde
    FR: { type:'free', name:'Vizesiz (AB/Schengen)', duration:9999, fee:null, notes:'İsviçre pasaportuyla tüm Schengen bölgesi serbest.' },
    ES: { type:'free', name:'Vizesiz (AB/Schengen)', duration:9999, fee:null },
    IT: { type:'free', name:'Vizesiz (AB/Schengen)', duration:9999, fee:null },
    DE: { type:'free', name:'Vizesiz (AB/Schengen)', duration:9999, fee:null },
    GR: { type:'free', name:'Vizesiz (AB/Schengen)', duration:9999, fee:null },
    PT: { type:'free', name:'Vizesiz (AB/Schengen)', duration:9999, fee:null },
    NL: { type:'free', name:'Vizesiz (AB/Schengen)', duration:9999, fee:null },
    AT: { type:'free', name:'Vizesiz (AB/Schengen)', duration:9999, fee:null },
  },
  DE: { // Alman pasaportu
    ID: { type:'voa', name:'Vize on Arrival', duration:30, fee:'500.000 IDR (~€30)', extendable:true },
    TH: { type:'free', name:'Vizesiz', duration:30, fee:null },
    JP: { type:'free', name:'Vizesiz', duration:90, fee:null },
    SG: { type:'free', name:'Vizesiz', duration:90, fee:null },
    VN: { type:'free', name:'Vizesiz', duration:45, fee:null },
    IN: { type:'evisa', name:'e-Vize', duration:60, fee:'25 USD' },
    US: { type:'esta', name:'ESTA', duration:90, fee:'$21', notes:'esta.cbp.dhs.gov' },
    CA: { type:'eta', name:'eTA', duration:180, fee:'CAD 7' },
    AU: { type:'eta', name:'ETA', duration:90, fee:'AUD 20' },
    NZ: { type:'nzeta', name:'NZeTA', duration:90, fee:'NZD 23' },
    GB: { type:'visa', name:'ETA (Elektronik Seyahat İzni)', duration:180, fee:'£10', notes:'2024\'ten itibaren gerekli.' },
    MA: { type:'free', name:'Vizesiz', duration:90, fee:null },
    EG: { type:'voa', name:'Vize on Arrival', duration:30, fee:'25 USD' },
    ZA: { type:'free', name:'Vizesiz', duration:90, fee:null },
    AE: { type:'free', name:'Vizesiz', duration:90, fee:null },
    MX: { type:'free', name:'Vizesiz', duration:180, fee:null },
    BR: { type:'free', name:'Vizesiz', duration:90, fee:null },
    FR: { type:'free', name:'Vizesiz (AB/Schengen)', duration:9999, fee:null },
    ES: { type:'free', name:'Vizesiz (AB/Schengen)', duration:9999, fee:null },
    IT: { type:'free', name:'Vizesiz (AB/Schengen)', duration:9999, fee:null },
    GR: { type:'free', name:'Vizesiz (AB/Schengen)', duration:9999, fee:null },
    PT: { type:'free', name:'Vizesiz (AB/Schengen)', duration:9999, fee:null },
    NL: { type:'free', name:'Vizesiz (AB/Schengen)', duration:9999, fee:null },
    AT: { type:'free', name:'Vizesiz (AB/Schengen)', duration:9999, fee:null },
  },
};

// IATA → 2 harfli ülke kodu
const IATA_COUNTRY = {
  DPS:'ID',CGK:'ID',SUB:'ID',UPG:'ID',
  BKK:'TH',HKT:'TH',CNX:'TH',USM:'TH',KBI:'TH',
  NRT:'JP',KIX:'JP',CTS:'JP',FUK:'JP',OKA:'JP',NGO:'JP',
  SIN:'SG',
  SGN:'VN',HAN:'VN',DAD:'VN',VDH:'VN',
  KUL:'MY',PEN:'MY',LGK:'MY',
  DEL:'IN',BOM:'IN',MAA:'IN',BLR:'IN',CCU:'IN',HYD:'IN',GOI:'IN',
  RGN:'MM',
  PNH:'KH',REP:'KH',
  MNL:'PH',CEB:'PH',DVO:'PH',
  CMB:'LK',
  MLE:'MV',
  KTM:'NP',
  DXB:'AE',AUH:'AE',SHJ:'AE',
  DOH:'QA',
  AMM:'JO',AQJ:'JO',
  EVN:'AM',
  TBS:'GE',BUS:'GE',
  GYD:'AZ',
  TAS:'UZ',SKD:'UZ',
  CDG:'FR',ORY:'FR',NCE:'FR',LYS:'FR',MRS:'FR',BOD:'FR',TLS:'FR',NTE:'FR',
  MAD:'ES',BCN:'ES',AGP:'ES',PMI:'ES',VLC:'ES',SVQ:'ES',TFS:'ES',LPA:'ES',IBZ:'ES',
  FCO:'IT',MXP:'IT',VCE:'IT',NAP:'IT',BLQ:'IT',PSA:'IT',FLR:'IT',CTA:'IT',PMO:'IT',
  FRA:'DE',MUC:'DE',BER:'DE',DUS:'DE',HAM:'DE',CGN:'DE',STR:'DE',NUE:'DE',TXL:'DE',
  LHR:'GB',LGW:'GB',MAN:'GB',EDI:'GB',BHX:'GB',LTN:'GB',STN:'GB',GLA:'GB',
  ATH:'GR',HER:'GR',RHO:'GR',SKG:'GR',CFU:'GR',KGS:'GR',JMK:'GR',JTR:'GR',CHQ:'GR',
  LIS:'PT',OPO:'PT',FAO:'PT',FNC:'PT',
  AMS:'NL',RTM:'NL',EIN:'NL',
  ZRH:'CH',GVA:'CH',BSL:'CH',
  VIE:'AT',GRZ:'AT',INN:'AT',SZG:'AT',
  BRU:'BE',CRL:'BE',
  OSL:'NO',BGO:'NO',TRD:'NO',
  ARN:'SE',GOT:'SE',MMX:'SE',
  CPH:'DK',BLL:'DK',AAL:'DK',
  HEL:'FI',TMP:'FI',
  PRG:'CZ',BRQ:'CZ',
  WAW:'PL',KRK:'PL',GDN:'PL',WRO:'PL',
  BUD:'HU',DEB:'HU',
  ZAG:'HR',SPU:'HR',DBV:'HR',
  JFK:'US',LAX:'US',ORD:'US',MIA:'US',SFO:'US',LAS:'US',MCO:'US',SEA:'US',BOS:'US',DFW:'US',ATL:'US',IAH:'US',PHX:'US',EWR:'US',
  YYZ:'CA',YVR:'CA',YUL:'CA',YYC:'CA',YEG:'CA',
  CUN:'MX',MEX:'MX',GDL:'MX',MTY:'MX',SJD:'MX',
  GRU:'BR',GIG:'BR',SSA:'BR',REC:'BR',FOR:'BR',BSB:'BR',POA:'BR',
  EZE:'AR',AEP:'AR',COR:'AR',MDP:'AR',
  HAV:'CU',
  RAK:'MA',CMN:'MA',AGA:'MA',TNG:'MA',
  CAI:'EG',HRG:'EG',SSH:'EG',LXR:'EG',ASW:'EG',
  TUN:'TN',NBE:'TN',
  CPT:'ZA',JNB:'ZA',DUR:'ZA',
  NBO:'KE',MBA:'KE',
  ADD:'ET',
  SYD:'AU',MEL:'AU',BNE:'AU',PER:'AU',ADL:'AU',CNS:'AU',OOL:'AU',
  AKL:'NZ',CHC:'NZ',WLG:'NZ',ZQN:'NZ',
  NAN:'FJ',SUV:'FJ',
};

export default function handler(req, res) {
  const { passport = 'TR', destination } = req.query;
  if (!destination) return res.status(400).json({ error: 'destination IATA kodu zorunludur' });

  const passportUpper = passport.toUpperCase();
  const destIATA = destination.toUpperCase();
  
  // IATA'dan ülke kodunu bul
  const destCountryCode = IATA_COUNTRY[destIATA] || destIATA.slice(0, 2);
  
  const passportData = VISA_DATA[passportUpper];
  if (!passportData) return res.status(200).json({ found:false, message:`${passport} pasaportu için veri bulunamadı. Konsolosluğunuzu kontrol edin.` });

  const visaInfo = passportData[destCountryCode];
  if (!visaInfo) return res.status(200).json({ found:false, passport:passportUpper, destination:destIATA, country_code:destCountryCode, message:`${passportUpper} pasaportu için ${destCountryCode} vizesi hakkında bilgimiz yok. İlgili konsolosluğun web sitesini kontrol edin.` });

  return res.status(200).json({ found:true, passport:passportUpper, destination:destIATA, country_code:destCountryCode, ...visaInfo });
}
